---
- name: Install common desktop packages
  apt:
    name:
      - xserver-xorg
      - x11-common
      - i3
      - i3-wm
      - i3lock
      - i3status
      - slim
      - dbus-x11
      - google-chrome-stable
      - krdc
      - feh
      - arandr
      - rdesktop
      - dnscrypt-proxy
      - dnscrypt-proxy-plugins
      - mkusb
      - terminator
      - irssi
      - pulseaudio
      - alsa-utils
    state: latest


- name: Install extra desktop packages
  apt:
    name:
      - libdvdcss2
      - libdvdnav4
      - libdvdread4
      - k3b
      - libreoffice
      - ledger
      - obs-studio
      - dvd+rw-tools
    state: present
