---
# Set ipv6 disabled for all defined interfaces
- sysctl:
    name: "net.ipv6.conf.{{ifname}}.disable_ipv6"
    value: 1
    sysctl_set: yes
    state: present
  with_items:
    - "{{ ansible_interfaces }}"
    - "default"
    - "all"
  loop_control:
    loop_var: ifname
