---
- name: Enable Duo Security
  include_tasks: setup_duo_security.yml
  when: (enable_2FA is defined and enable_2FA and enable_2FA == true)

- name: Enable Automatic Security Updates
  include_tasks: automatic_security_updates_ubuntu.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Secure Default SSHD Config
  include_tasks: 
    file: secure_sshd_server.yml
    apply:
      tags: 
        - ssh
        - lockdown
        - secure_configs
  tags:
    - always

- name: Turn off ipv6 functionality
  include_tasks:
    file: disable_ipv6.yml
    apply:
      tags:
        - secure_configs
        - disable_ipv6
        - no_ipv6
  tags:
   - always
  when: (enable_ipv6 is undefined or (enable_ipv6 is defined and enable_ipv6 != "true"))
