---
- name: Set SSH Banner
  copy: src=issue dest=/etc/issue owner=root group=root mode=0744

- name: Set SSH Configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes
  with_items:
    - "{{ sshd_config }}"
  notify:
      - restart sshd
      - restart ssh
  when: sshd_config is defined and sshd_config
  register: sshd
